name: 'Quick K8s'
description: 'Quickly deploy a k8s cluster on Github Actions hosted runners'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  apiServerPort:
    description: 'The port to use for the Kubernetes API server'
    required: false
    default: '6443'
  apiServerAddress:
    description: 'The address to use for the Kubernetes API server'
    required: false
    default: '0.0.0.0'
  disableDefaultCni:
    description: 'Disable the default CNI plugin'
    required: false
    default: 'true'
  ipFamily:
    description: 'The IP family to use for the Kubernetes API server'
    required: false
    default: 'dual'
  defaultNodeImage:
    description: 'The default node image to use for the Kubernetes cluster'
    required: false
    default: 'kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a'
  numControlPlaneNodes:
    description: 'The number of control plane nodes to use for the Kubernetes cluster'
    required: false
    default: '1'
  numWorkerNodes:
    description: 'The number of worker nodes to use for the Kubernetes cluster'
    required: false
    default: '1'
  clusterProvider:
    description: 'Kubernetes cluster provider (kind or minikube)'
    required: false
    default: 'kind'
  kindVersion:
    description: 'The version of KinD to use'
    required: false
    default: 'v0.30.0'
  minikubeVersion:
    description: 'The version of Minikube to use'
    required: false
    default: 'v1.37.0'
  minikubeDriver:
    description: 'The driver to use for Minikube (docker, podman, none)'
    required: false
    default: 'docker'
  calicoVersion:
    description: 'The version of Calico to use'
    required: false
    default: 'v3.31.2'
  ocpReleaseLevel:
    description: 'The release level of OpenShift to use'
    required: false
    default: '4.19'
  installOLM:
    description: 'Install the Operator Lifecycle Manager'
    required: false
    default: 'false'
  removeDefaultStorageClass:
    description: 'Remove the default storage class'
    required: false
    default: 'false'
  removeControlPlaneTaint:
    description: 'Remove the control plane taint'
    required: false
    default: 'false'
  waitForPodsReady:
    description: 'Wait for all pods to be ready'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Validate cluster provider input
      shell: bash
      run: |
        if [[ "${{ inputs.clusterProvider }}" != "kind" && "${{ inputs.clusterProvider }}" != "minikube" ]]; then
          echo "Invalid cluster provider: ${{ inputs.clusterProvider }}"
          echo "Must be either 'kind' or 'minikube'"
          exit 1
        fi

    - name: Validate KinD version input
      if: ${{ inputs.clusterProvider == 'kind' }}
      shell: bash
      run: |
        if ! [[ "${{ inputs.kindVersion }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid KinD version format: ${{ inputs.kindVersion }}"
          exit 1
        fi
        if ! curl --silent --fail -L https://api.github.com/repos/kubernetes-sigs/kind/releases/tags/${{ inputs.kindVersion }} > /dev/null; then
          echo "KinD version ${{ inputs.kindVersion }} does not exist on GitHub"
          exit 1
        fi

    - name: Validate Minikube version input
      if: ${{ inputs.clusterProvider == 'minikube' }}
      shell: bash
      run: |
        if ! [[ "${{ inputs.minikubeVersion }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid Minikube version format: ${{ inputs.minikubeVersion }}"
          exit 1
        fi
        if ! curl --silent --fail -L https://api.github.com/repos/kubernetes/minikube/releases/tags/${{ inputs.minikubeVersion }} > /dev/null; then
          echo "Minikube version ${{ inputs.minikubeVersion }} does not exist on GitHub"
          exit 1
        fi

    - name: Validate Calico version input
      shell: bash
      run: |
        if ! [[ "${{ inputs.calicoVersion }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid Calico version format: ${{ inputs.calicoVersion }}"
          exit 1
        fi
        if ! curl --silent --fail -L https://api.github.com/repos/projectcalico/calico/releases/tags/${{ inputs.calicoVersion }} > /dev/null; then
          echo "Calico version ${{ inputs.calicoVersion }} does not exist on GitHub"
          exit 1
        fi

    - name: Validate OpenShift release level input
      shell: bash
      run: |
        if ! [[ "${{ inputs.ocpReleaseLevel }}" =~ ^[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid OpenShift release level format: ${{ inputs.ocpReleaseLevel }}"
          exit 1
        fi

    - name: Validate number of control-plane nodes
      shell: bash
      run: |
        if [[ "${{ inputs.numControlPlaneNodes }}" -lt 1 ]]; then
          echo "The number of control-plane nodes cannot be less than 1."
          exit 1
        fi

    - name: Validate number of worker nodes
      shell: bash
      run: |
        if [[ "${{ inputs.numWorkerNodes }}" -lt 0 ]]; then
          echo "The number of worker nodes cannot be negative."
          exit 1
        fi

    - name: Check GitHub service status
      shell: bash
      run: ${{ github.action_path }}/scripts/check-github-status.sh

    - name: Write temporary docker file (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        mkdir -p /home/runner/.docker
        touch /home/runner/.docker/config

    - name: Proactive Disk Space Management (Ubuntu)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/proactive-disk-cleanup.sh

    - name: Setup Docker on Mac
      if: ${{ runner.os == 'macOS' }}
      uses: douglascamata/setup-docker-macos-action@v1-alpha

    # Cache KinD binary to avoid download failures during outages
    - name: Cache KinD binary
      if: ${{ inputs.clusterProvider == 'kind' }}
      id: cache-kind
      uses: actions/cache@v4
      with:
        path: /tmp/kind-binary
        key: kind-${{ inputs.kindVersion }}-${{ runner.os }}-${{ runner.arch }}

    # Install KinD binary (unified script for all platforms)
    - name: Install KinD
      if: ${{ inputs.clusterProvider == 'kind' }}
      shell: bash
      run: |
        OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        ${{ github.action_path }}/scripts/install-kind.sh ${{ inputs.kindVersion }} "$OS" ${{ runner.arch }}

    - name: Add error handling for KinD installation
      if: ${{ inputs.clusterProvider == 'kind' }}
      shell: bash
      run: |
        if ! command -v kind &> /dev/null; then
          echo "KinD installation failed. Exiting."
          exit 1
        fi

    # Cache Minikube binary to avoid download failures during outages
    - name: Cache Minikube binary
      if: ${{ inputs.clusterProvider == 'minikube' }}
      id: cache-minikube
      uses: actions/cache@v4
      with:
        path: /tmp/minikube-binary
        key: minikube-${{ inputs.minikubeVersion }}-${{ runner.os }}-${{ runner.arch }}

    # Install Minikube binary (unified script for all platforms)
    - name: Install Minikube
      if: ${{ inputs.clusterProvider == 'minikube' }}
      shell: bash
      run: |
        OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        ${{ github.action_path }}/scripts/install-minikube.sh ${{ inputs.minikubeVersion }} "$OS" ${{ runner.arch }}

    - name: Add error handling for Minikube installation
      if: ${{ inputs.clusterProvider == 'minikube' }}
      shell: bash
      run: |
        if ! command -v minikube &> /dev/null; then
          echo "Minikube installation failed. Exiting."
          exit 1
        fi

    # Create a new Kubernetes cluster using KinD
    - name: Populate temporary config file for KinD
      if: ${{ inputs.clusterProvider == 'kind' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/generate-kind-config.sh ${{ inputs.apiServerPort }} ${{ inputs.apiServerAddress }} ${{ inputs.disableDefaultCni }} ${{ inputs.ipFamily }} ${{ inputs.defaultNodeImage }} ${{ inputs.numControlPlaneNodes }} ${{ inputs.numWorkerNodes }} ${{ github.action_path }}/kind-config.yaml

    - name: Print the KinD config
      if: ${{ inputs.clusterProvider == 'kind' }}
      shell: bash
      run: cat ${{ github.action_path }}/kind-config.yaml

    - name: Bootstrap the docker instance on the runner (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/bootstrap-docker.sh

    - name: Final pre-cluster disk optimization
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/pre-cluster-optimization.sh

    - name: Create a new Kubernetes cluster using KinD
      if: ${{ inputs.clusterProvider == 'kind' }}
      shell: bash
      run: kind create cluster --config ${{ github.action_path }}/kind-config.yaml

    - name: Create a new Kubernetes cluster using Minikube
      if: ${{ inputs.clusterProvider == 'minikube' }}
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/start-minikube.sh \
          "${{ inputs.defaultNodeImage }}" \
          "${{ inputs.disableDefaultCni }}" \
          "${{ inputs.minikubeDriver }}" \
          "${{ inputs.apiServerPort }}" \
          "${{ inputs.numControlPlaneNodes }}" \
          "${{ inputs.numWorkerNodes }}"

    # - name: Bootstrap the runner with kubectl and oc clients
    - name: Bootstrap the runner with kubectl and oc clients
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo ${{ github.action_path }}/scripts/install-oc-tools.sh --latest ${{ inputs.ocpReleaseLevel }}

    - name: Install oc client on MacOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install openshift-cli
        brew install kubernetes-cli

    - name: Install calico CNI if default CNI is disabled
      if: ${{ inputs.disableDefaultCni == 'true' }}
      shell: bash
      run: |
        oc apply -f https://raw.githubusercontent.com/projectcalico/calico/$CALICO_VERSION/manifests/calico.yaml;
      env:
        CALICO_VERSION: ${{ inputs.calicoVersion }}

    - name: Install OLM
      if: ${{ inputs.installOLM == 'true' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/install-olm.sh

    - name: Remove the default storage class
      if: ${{ inputs.removeDefaultStorageClass == 'true' }}
      shell: bash
      run: |
        oc delete storageclass standard --ignore-not-found

    - name: Remove the control plane taint
      if: ${{ inputs.removeControlPlaneTaint == 'true' }}
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/remove-control-plane-taint.sh

    - name: Wait for all pods to be ready
      if: ${{ inputs.waitForPodsReady == 'true' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/wait-for-pods.sh

    - name: Clean up package manager cache (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get clean

    - name: Clean up Homebrew cache (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew cleanup -s
        rm -rf ~/Library/Caches/Homebrew

    - name: Remove temporary files
      shell: bash
      run: |
        rm -f ${{ github.action_path }}/kind-config.yaml || true
        rm -f oc.tar.gz kind || true
